* 삶의 만족도, happy_life
* 건강, happy_health
* 안전, happy_safe
* 환경, happy_environ
* 경제, happy_econo
* 교육, happy_edu
* 관계 및 사화참여, happy_relation
* 여가, happy_leisure
* ==> happy_merge

In [17]:
import pandas as pd
import os

path = 'happy/'
file_list = os.listdir(path)

file_list
# happy_life = pd.read_excel('happy\대한민국행복지도_삶의만족도.xlsx', engine='openpyxl')
# happy_health = pd.read_excel('happy\대한민국행복지도_건강.xlsx', engine='openpyxl') 
# happy_safe = pd.read_excel('happy\대한민국행복지도_안전.xlsx', engine='openpyxl') 
# happy_environ = pd.read_excel('happy\대한민국행복지도_환경.xlsx', engine='openpyxl')
# happy_econo = pd.read_excel('happy\대한민국행복지도_경제.xlsx', engine='openpyxl')
# happy_edu = pd.read_excel('happy\대한민국행복지도_교육.xlsx', engine='openpyxl')
# happy_realation = pd.read_excel('happy\대한민국행복지도_관계 및 사회참여.xlsx', engine='openpyxl')
# happy_leisure = pd.read_excel('happy\대한민국행복지도_여가.xlsx', engine='openpyxl')

['대한민국행복지도_건강.xlsx',
 '대한민국행복지도_경제.xlsx',
 '대한민국행복지도_관계 및 사회참여.xlsx',
 '대한민국행복지도_교육.xlsx',
 '대한민국행복지도_삶의만족도.xlsx',
 '대한민국행복지도_안전.xlsx',
 '대한민국행복지도_여가.xlsx',
 '대한민국행복지도_환경.xlsx']

In [18]:
import pandas as pd

happy_life = pd.read_excel('happy\대한민국행복지도_삶의만족도.xlsx', engine='openpyxl')
life_merge = happy_life.groupby('시도')[['삶의 만족도']].mean()
life_merge.head()

# life_merge = pd.merge(life_merge,health_merge(columns={'평균':'건강'}), on='시도')

         삶의 만족도
시도
강원도    0.619506
경기도    0.426023
경상남도   0.530794
경상북도   0.502223
광주광역시  0.484480

In [20]:
keywords = {'건강': 'happy_health', '안전':'happy_safe', '환경':'happy_environ','경제':'happy_econo',
            '교육':'happy_edu', '관계및사회참여':'happy_realation','여가':'happy_leisure'}

try:
    for i in file_list:
        if i.endswith('.xlsx'):
            for x, y in keywords.items():
                if x in i:
                    keywords[x]= pd.read_excel(path+i, engine='openpyxl')

                    health = keywords[x].groupby('시도')[['평균']].mean()

                    life_merge = pd.merge(life_merge,health.rename(columns={'평균':x}), on='시도')

except:
    print(i)

life_merge

,삶의 만족도,건강_x,경제_x,교육_x,안전_x,여가_x,환경_x,건강_y,경제_y,교육_y,안전_y,여가_y,환경_y
시도,,,,,,,,,,,,,
강원도,0.619506,0.329506,0.386861,0.488533,0.548000,0.632750,0.639839,0.329506,0.386861,0.488533,0.548000,0.632750,0.639839
경기도,0.426023,0.353952,0.468926,0.668619,0.325255,0.377561,0.557977,0.353952,0.468926,0.668619,0.325255,0.377561,0.557977
경상남도,0.530794,0.312722,0.325017,0.624022,0.475561,0.463750,0.735600,0.312722,0.325017,0.624022,0.475561,0.463750,0.735600
경상북도,0.502223,0.264114,0.303355,0.428252,0.484835,0.490804,0.614265,0.264114,0.303355,0.428252,0.484835,0.490804,0.614265
광주광역시,0.484480,0.632300,0.387380,0.689680,0.266440,0.454980,0.607480,0.632300,0.387380,0.689680,0.266440,0.454980,0.607480
대구광역시,0.363988,0.482325,0.393975,0.585838,0.358429,0.234925,0.552500,0.482325,0.393975,0.585838,0.358429,0.234925,0.552500
대전광역시,0.407580,0.663580,0.416260,0.840780,0.206780,0.347960,0.582380,0.663580,0.416260,0.840780,0.206780,0.347960,0.582380
부산광역시,0.362081,0.511906,0.438038,0.504594,0.404875,0.153587,0.448719,0.511906,0.438038,0.504594,0.404875,0.153587,0.448719
서울특별시,0.490972,0.569532,0.532820,0.399412,0.552256,0.286732,0.470712,0.569532,0.532820,0.399412,0.552256,0.286732,0.470712
세종특별자치시,0.907700,0.232000,0.511900,0.587000,0.157800,0.447800,0.652400,0.232000,0.511900,0.587000,0.157800,0.447800,0.652400
울산광역시,0.471980,0.420040,0.642580,0.763240,0.477060,0.418420,0.393440,0.420040,0.642580,0.763240,0.477060,0.418420,0.393440
인천광역시,0.411480,0.339620,0.410820,0.502920,0.421020,0.244590,0.515020,0.339620,0.410820,0.502920,0.421020,0.244590,0.515020
전라남도,0.547709,0.424732,0.202668,0.420019,0.565195,0.658668,0.700573,0.424732,0.202668,0.420019,0.565195,0.658668,0.700573
전라북도,0.608193,0.421300,0.196543,0.446936,0.410914,0.667900,0.670586,0.421300,0.196543,0.446936,0.410914,0.667900,0.670586
제주특별자치도,0.711300,0.253700,0.425000,0.646800,0.446100,0.694800,0.684200,0.253700,0.425000,0.646800,0.446100,0.694800,0.684200
충청남도,0.553100,0.347433,0.402893,0.648047,0.481313,0.625347,0.558173,0.347433,0.402893,0.648047,0.481313,0.625347,0.558173
충청북도,0.410100,0.401064,0.484755,0.592409,0.573155,0.702891,0.466045,0.401064,0.484755,0.592409,0.573155,0.702891,0.466045

In [ ]:
# life_merge = happy_life.groupby('시도')[['삶의 만족도']].mean()
# health_merge = happy_health.groupby('시도')[['건강']].mean()
# safe_merge = happy_safe.groupby('시도')[['안전']].mean()
# environ_merge = happy_environ.groupby('시도')[['환경']].mean()
# econo_merge = happy_econo.groupby('시도')[['경제']].mean()
# edu_merge = happy_edu.groupby('시도')[['교육']].mean()
# relation_merge = happy_realation.groupby('시도')[['관계']].mean()
# leisure_merge = happy_edu.leisure('시도')[['여가']].mean()


# happy_merge = happy_life.groupby('시도')[['삶의 만족도','건강강']].mean()


life_merge = pd.merge(life_merge,health_merge(columns={'평균':'건강'}), on='시도')